authapp/urls.py
from django.urls import path
from authapp.views import login, register, logout, profile

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index, products

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp.views import products, detail

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='products'),
    path('detail/', detail, name='detail'),
]

mainapp/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    name = models.CharField(max_length=128)
    image = models.ImageField(upload_to='product_image', blank=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} | {self.category}'

mainapp/views.py
from django.shortcuts import render
from .models import ProductCategory, Product

# Create your views here.


def index(request):
    context = {
        'title': 'GeekShop',
    }
    return render(request, 'mainapp/index.html', context)


def products(request):
    context = {
        'title': 'GeekShop | Каталог',
        'products': Product.objects.all(),
        'categories': ProductCategory.objects.all(),
    }
    return render(request, 'mainapp/products.html', context)

def detail(request):
    context = {
        'products': Product.objects.all(),
    }
    return render(request, 'mainapp/detail.html', context)

mainapp/templates/mainapp/includes/card.html
<div class="card_add_basket">

    <div class="row">
        {% for product in products %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <a href="{% url 'mainapp:detail' %}">
                        <img class="card-img-top" src="{{ product.image.url }}" alt="">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="{% url 'mainapp:detail' %}">{{ product.name }}</a>
                        </h4>
                        <h5>{{ product.price }} руб.</h5>
                        <p class="card-text">{{ product.description }}</p>
                    </div>
                    <div class="card-footer text-center">
                        <button type="button" class="btn btn-outline-success" value="{{ product.id }}">
                            Отправить в корзину
                        </button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>